# ---- Execution Mode ----
cluster_mode = true

# ---- Directories ----
inversion_dir = computing

# ---- SLURM ----
slurm_script = run.slurm

# ---- Automation ----
auto_post = false
post_data = rho_phase
