#!/usr/bin/env python3

import subprocess
import argparse
import tomllib
import shutil
import sys
import os

MAKETETRAMESH_URL = "https://github.com/yoshiya-usui/makeTetraMesh.git"
TETGEN2FEMTIC_URL = "https://github.com/yoshiya-usui/TetGen2Femtic.git"
MAKEMTR_URL_URL = "https://github.com/yoshiya-usui/makeMtr.git"
MERGERESULT_URL = "https://github.com/yoshiya-usui/mergeResultOfFEMTIC.git"
FEMTIC_URL = "https://github.com/yoshiya-usui/femtic.git"
TETGEN_URL = "https://github.com/TetGen/TetGen.git"


def read_config():
    try:
        with open("mtif.toml", "rb") as f:
            config = tomllib.load(f)
        return config
    except FileNotFoundError:
        print("ERROR: mtif.toml not found.")
        sys.exit(1)

def update_meshtran_io_from_toml(config,mesh_type):
    mesh_cfg = config["mesh"]

    #from TOML to io
    replacements = {
        
        "MESH_NATURE": mesh_type,
        "DEM_FILE": mesh_cfg["dem_file"],
        "DEM_UNITS": mesh_cfg["dem_units"],
        "XMIN_DOM": mesh_cfg["domain_x"][0],
        "XMAX_DOM": mesh_cfg["domain_x"][1],
        "YMIN_DOM": mesh_cfg["domain_y"][0],
        "YMAX_DOM": mesh_cfg["domain_y"][1],
        "ZMIN_DOM": mesh_cfg["domain_z"][0],
        "ZMAX_DOM": mesh_cfg["domain_z"][1],
        "PAD_X":mesh_cfg["pad_x"],
        "PAD_Y": mesh_cfg["pad_y"],
        "HAS_SEA":"YES" if mesh_cfg["has_sea"]else "NO",
        "SEA_LEVEL": mesh_cfg["sea_level"],
        "TET_REFINEMENT": mesh_cfg["tet_refinement"],
        "TOPO_FILE": mesh_cfg["topo_file"],
        "BATHY_FILE": mesh_cfg["bathy_file"],
        "COSLI_FILE": mesh_cfg["coast_file"],
    }
    with open("bin/set_meshtran.io","r") as f:
        lines = f.readlines()
    
    new_lines = []
    
    for line in lines:
        stripped = line.strip()

        if "=" in stripped:
            key = stripped.split("=")[0].strip()

            if key in replacements:
                new_value = replacements[key] 
                new_line = f"{key} = {new_value}\n"
                new_lines.append(new_line)
                continue

        new_lines.append(line)

    with open("bin/set_meshtran.io", "w") as f:
        f.writelines(new_lines)

    print(" 📖 set_meshtran.io updated from mtif.toml")



#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#
# Comando para construir la malla 
#
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
def run_mesh(args):
# --- MODO CHECK ---
    if args.check:
        target_path = os.path.join("bin", "check_domain.py")
        if os.path.exists(target_path):
            print("     == Checking mesh geometry ==")
            subprocess.run(["python3", "bin/check_domain.py"], check=True)
        else:
            print("plot_inputs.py not found.")
        return   # <-- IMPORTANTE (sale de la función)


    target_path = os.path.join( "preprocessing", "buildMesh", "reindexing_tetgen.py")
    if not os.path.exists(target_path):
        print(f"ERROR: reindexing_tetgen.py not found at {target_path}")
        sys.exit(1)

    if not os.path.exists("bin/set_meshtran.io"):
        print("ERROR: set_meshtran.io not found.")
        sys.exit(1)


    config = read_config()
    mesh_cfg = config["mesh"]

    mesh_type = args.mesh if args.mesh else mesh_cfg["default_mesh"]

    print("== Updating set_meshtran.io from mtif.toml ==")
    update_meshtran_io_from_toml(config, mesh_type)
    
    print("     == Running meshTran ==")
    subprocess.run(["bin/meshTranPreprocessing"], check=True)

    # if os.path.exists("plot_inputs.py"):
    #     print("== Plotting input geometry ==")
    #     subprocess.run(["python3", "plot_inputs.py"], check=True)



#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#
# Revisar herramientas necesarias en el sistema
#
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
def run_inversion(config):
    inversion_dir = config.get("inversion_dir", "computing")
    cluster_mode = config.get("cluster_mode", "false").lower() == "true"
    slurm_script = config.get("slurm_script", "run.slurm")

    if not os.path.exists(inversion_dir):
        print(f"ERROR: inversion directory '{inversion_dir}' not found.")
        sys.exit(1)

    if cluster_mode:
        slurm_path = os.path.join(inversion_dir, slurm_script)
        if not os.path.exists(slurm_path):
            print(f"ERROR: SLURM script '{slurm_path}' not found.")
            sys.exit(1)

        print("== Submitting job to SLURM ==")
        subprocess.run(["sbatch", slurm_path], check=True)
    else:
        print("== Running FEMTIC locally ==")
        subprocess.run(["femtic"], cwd=inversion_dir, check=True)


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#
# Comando para lanzar el postprocesado
#
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
def run_post(args):
    print("== Running Postprocessing ==")
    config = read_config()
    post_cfg = config["post"]

    job = args.job if args.job else post_cfg["last_job"]
    sites = args.sites if args.sites else post_cfg["default_sites"]
    iters = args.iter if args.iter else post_cfg["default_iter"]
    procs = args.proc if args.proc else post_cfg["default_proc"]
    xaxis = args.axis if args.axis else post_cfg["default_axis"]

    
    if args.mode is not None:
        mode = args.mode                        #Si usuario pasa --mode impz → usa impz
    elif config.get("default_mode") in ["impz", "rhoph"]:
        mode = config.get("default_mode")       #Si no pasa nada y el config tiene impz o rhoph → usa eso
    else:
        mode = "none"                           #Si no hay nada válido → usa "none"

    results_path = f"{post_cfg['post_path']}/{job}"
    st_arg = f"st{sites}"
    ip_arg = f"ip{iters}-{procs}"


    print("   Results folder: ",results_path)
    print("   Job:", job)
    print("   Sites:", sites)
    print("   Mode:", mode)

    cmd = ["./bin/MTpostprocess.py", results_path, st_arg, ip_arg, xaxis ] 

    # mode = str(mode)
    if mode != "none":
      cmd.append(mode)


    subprocess.run(cmd, check=True)

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#
# Revisar herramientas necesarias en el sistema
#
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
def check_tool(tool_name):
    if shutil.which(tool_name) is None:
        print(f"ERROR: Required tool '{tool_name}' not found in PATH.")
        sys.exit(1)


def check_environment():
    print("== Checking required tools ==")

    required_tools = ["git", "make"]

    for tool in required_tools:
        check_tool(tool)

    # compilador
    if shutil.which("gfortran") is None and shutil.which("ifort") is None:
        print("ERROR: No Fortran compiler found (gfortran or ifort).")
        sys.exit(1)

    print("Environment OK.\n")

def clone_repo(url, path):
    if not os.path.exists(path):
        print(f"Cloning {url} into {path}")
        subprocess.run(["git", "clone", url, path], check=True)
    else:
        print(f"{path} already exists. Skipping clone.")

    # shutil.copy(f"{path}dependencies/femtic/femtic", "bin/")


def run_install():
    check_environment()
    os.makedirs("dependencies",exist_ok=True)
    os.makedirs("bin", exist_ok=True)
    if not os.path.exists("dependencies/femtic"):
        subprocess.run(["git", "clone", FEMTIC_URL, "dependencies/femtic"], check=True)
    # subprocess.run(["patch", "Makefile", "../../patches/femtic.patch"],
    #                cwd="dependencies/femtic",
    #                check=True)

        # Sustituir Makefile original por el tuyo
    if os.path.exists("patches/Makefile_IntelMPI"):
        print("Replacing FEMTIC Makefile with Makefile_IntelMPI")
        shutil.copy(
            "patches/Makefile_IntelMPI",
            "dependencies/femtic/src/Makefile"
        )
    else:
        print("Makefile_IntelMPI not found in patches/")
        sys.exit(1)
    subprocess.run(["make"], cwd="dependencies/femtic/src", check=True)
    shutil.copy("dependencies/femtic/src/femtic", "bin/")
    print("FEMTIC installed correctly.")


def run_new(project_name):
    if os.path.exists(project_name):
        print(f"Error: Folder '{project_name}' already exists.")
        sys.exit(1)
    print(" ")
    print(f" Creating new MTIF project: {project_name}")
   
    os.makedirs(os.path.join(project_name, "preprocessing"))
    os.makedirs(os.path.join(project_name, "preprocessing/PlotWithPython"))
    os.makedirs(os.path.join(project_name, "preprocessing/geometry"))
    os.makedirs(os.path.join(project_name, "preprocessing/inv"))
    os.makedirs(os.path.join(project_name, "preprocessing/DEM"))
    os.makedirs(os.path.join(project_name, "preprocessing/edi_files"))
    os.makedirs(os.path.join(project_name, "preprocessing/buildMesh"))
    os.makedirs(os.path.join(project_name, "computing"))
    os.makedirs(os.path.join(project_name, "patches"))
    os.makedirs(os.path.join(project_name, "postprocessing"))
    
    # Crear mtif.conf básico
    with open(os.path.join(project_name, "mtif.toml"), "w") as f:
        f.write(
        """
        [execution]
        cluster_mode = false
        inversion_dir = "computing"
        
        # ------------------------
        # SLURM
        # ------------------------
        [slurm]
        script = "run.slurm"
        
        # ------------------------
        # Mesh Defaults
        # ------------------------
        [mesh]
        default_mesh = "native"

        # ---- Domain ----
        domain_x = [0.0, 0.0]
        domain_y = [0.0, 0.0]
        domain_z = [0.0, 0.0]
        
        pad_x = 0.0
        pad_y = 0.0

        # ---- Topography ----
        dem_file = "file.xyz"
        dem_units = "kilometers"
        
        topo_file = "topography_for.dat"
        bathy_file = "bathymetry_for.dat"
        coast_file = "coast_line.dat"
        
        # ---- Sea ----
        has_sea = false
        sea_level = 0.0
        
        # ---- Refinement ----
        tet_refinement = x
        
        # ------------------------
        # Postprocessing
        # ------------------------
        [post]
        post_path = "postprocessing"
        auto_post = false
        post_data = "rho_phase"
        default_axis = "period"
        
        last_job = "job_284"
        default_sites = "M-N"
        default_mode = "none"
        default_iter = A
        default_proc = B
        """
        )
    
    print(f"     Project {project_name} created successfully.")
    print(f" now run:")
    print(f" cd {project_name}")
    print(" mtif install")






def main():
    parser = argparse.ArgumentParser(
        prog="mtif",
        description="""
    MTIF - Magnetotelluric Inversion Framework © 2026
    
 An Integrated framework for preprocessing, inversion and postprocessing of
    3D magnetotelluric data using FEMTIC as inversion engine.

    Author: Marco A Oliva Gutierrez
            University of Barcelona - Geomodels Research Institute
    """,
        epilog="""
    Examples:
      mtif create
      mtif install
      mtif mesh
      mtif run
      mtif post job_284 --sites 1-10 --mode impz --iter 8 --proc 2 --axis freq
    
    For detailed help on a command:
      mtif <command> --help
    """,
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "--version",
        action="version",
        version="MTIF v0.1.0"
    )



    subparsers = parser.add_subparsers(
    dest="command",
    required=True
    )
    # --------------------------------------------------
    # CREATE
    # --------------------------------------------------
    create_parser = subparsers.add_parser(
        "create",
        help="  Create a new MTIF project",
        description="Create a new MTIF project directory with predefined structure."
    )
    create_parser.add_argument(
        "project_name",
        help="Name of the new project directory"
    )
    
    # --------------------------------------------------
    # INSTALL
    # --------------------------------------------------
    install_parser = subparsers.add_parser(
        "install",
        help="Install required third-party dependencies",
        description="Clone and compile required tools such as FEMTIC and TetGen."
    )
    
    # --------------------------------------------------
    # MESH
    # --------------------------------------------------
    mesh_parser = subparsers.add_parser(
        "mesh",
        help="Run mesh preprocessing",
        description="Execute MeshTran preprocessing pipeline."
    )
    
    mesh_parser.add_argument(
        "--mesh",
        choices=["native", "external"],
        help="Site range (native (default)  or external)"
    )

    mesh_parser.add_argument(
        "--check",
        action="store_true",
        help="Only check and plot existing mesh (no mesh generation)"
    )
    
    # --------------------------------------------------
    # RUN
    # --------------------------------------------------
    run_parser = subparsers.add_parser(
        "run",
        help="Run inversion",
        description="Launch FEMTIC inversion locally or in cluster mode."
    )
    
    # --------------------------------------------------
    # POST
    # --------------------------------------------------
    post_parser = subparsers.add_parser(
        "post",
        help="Run postprocessing",
        description="Merged results and generate plots from inversion outputs."
    )
    
    post_parser.add_argument(
        "job",
        nargs="?",
        help="Job name (folder inside postprocessing)"
    )
    
    post_parser.add_argument(
        "--sites",
        help="Site range (e.g., 1-10)"
    )
    
    post_parser.add_argument(
        "--mode",
        choices=["impz", "rhoph"],
        help="Postprocessing mode"
    )
    
    post_parser.add_argument(
        "--iter",
        type=int,
        help="Number of iterations"
    )
    
    post_parser.add_argument(
        "--proc",
        type=int,
        help="Number of processes"
    )

    post_parser.add_argument(
        "--axis",
        help="Set x axis (e.g., freq or period)"
    )


    args = parser.parse_args()

    if args.command == "create":
        run_new(args.project_name)

    elif args.command == "install":
        run_install()

    elif args.command == "mesh":
        run_mesh(args)

    elif args.command == "run":
        config = read_config()
        run_inversion(config)

    elif args.command == "post":
        run_post(args)

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
