# ---- Execution Mode ----
cluster_mode = true

# ---- Directories ----
inversion_dir = computing

# ---- SLURM ----
slurm_script = run.slurm

# ---- Automation ----
post_path = postprocessing

# aqui la idea es que el inpout del python sea no la carpeta base sino de
# la base en adelante pues en teoria todo viviria en postrpcessing
auto_post = false
post_data = rho_phase

default_axis = period
last_job = job_284
default_sites = 1-10
default_mode = none
default_iter = 8
default_proc = 2

default_mesh = native

