[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "mtif"
version = "0.1.0"
description = "Magnetotelluric Inversion Framework using FEMTIC"
authors = [{ name = "Marco A. Oliva Gutierrez" }]
readme = "README.md"
requires-python = ">=3.10"


[project.scripts]
mtif = "mtif.cli:main"


[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
